# Generated by Django 5.2.1 on 2025-05-13 16:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('capacidad_pasajeros', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_departamento', models.CharField(max_length=10)),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('cod_municipio', models.CharField(max_length=10)),
                ('nombre_municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OcupacionTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llegada', models.DateTimeField(default=django.utils.timezone.now)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionTerminales.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='ocupacion_actual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_actual', to='gestionTerminales.ocupacionterminal'),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacidad', models.PositiveIntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTerminales.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='ocupacionterminal',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='gestionTerminales.terminal'),
        ),
        migrations.CreateModel(
            name='MovimientoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.FloatField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTerminales.bus')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llegadas', to='gestionTerminales.terminal')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='gestionTerminales.terminal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ocupacionterminal',
            unique_together={('terminal', 'bus')},
        ),
    ]
