# Generated by Django 5.2.1 on 2025-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTerminales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cod_departamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='cod_municipio',
            field=models.CharField(max_length=100),
        ),
    ]
