# Generated by Django 5.2.1 on 2025-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTerminales', '0003_alter_municipio_cod_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cod_departamento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='cod_municipio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('cod_departamento', 'cod_municipio')},
        ),
    ]
