# Generated by Django 5.2.1 on 2025-05-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTerminales', '0004_alter_municipio_cod_departamento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocupacionterminal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ocupacionterminal',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='ocupacionterminal',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='ocupacion_actual',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='coordenadas',
            new_name='ubicacion',
        ),
        migrations.AddField(
            model_name='bus',
            name='terminal_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses_presentes', to='gestionTerminales.terminal'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacidad_pasajeros',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='capacidad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTerminales.bus')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llegadas', to='gestionTerminales.terminal')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='gestionTerminales.terminal')),
            ],
        ),
        migrations.DeleteModel(
            name='MovimientoBus',
        ),
        migrations.DeleteModel(
            name='OcupacionTerminal',
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('origen', models.F('destino')), _negated=True), name='origen_distinto_de_destino'),
        ),
    ]
