# Generated by Django 5.2.1 on 2025-05-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTerminales', '0005_alter_ocupacionterminal_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='capacidad_pasajeros',
        ),
    ]
