# Generated by Django 5.2.1 on 2025-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTerminales', '0006_remove_bus_capacidad_pasajeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='ruta_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
